#include "../include/common/types.h"
#include <crow.h>
#include <iostream>
#include "../include/orderbook/OrderBookRB.h"

int main() {
   crow::SimpleApp app;

  CROW_ROUTE(app, "/")
  ([]() {
    Metrics exampleMetrics = {DataStructureName::RB_TREE,
                              12.5,
                              8.3,
                              5.1,
                              2.0,
                              45.7,
                              10.2,
                              25.8,
                              38.4,
                              8500.0,
                              100000,
                              2048576,
                              70000,
                              15000,
                              15000,
                              {5.2, 6.1, 12.3, 8.7, 15.4}};
    return to_json(exampleMetrics);
  });

  // Start server
  app.port(8080).multithreaded().run();
}

/*OrderBookSimulator/
├── README.md                   # Project overview, setup instructions
├── CMakeLists.txt              # Optional, for building C++ backend
├── data/
│   └── generate_data.cpp       # Script to generate random orders
├── include/
│   ├── common/
│   │   ├── macros.h            # Logging macros, constants
│   │   └── types.h             # Order struct, enums (Side, Type)
│   ├── orderbook/
│   │   ├── redblack_tree.h     # Red-Black Tree header
│   │   └── skiplist.h          # Skiplist header
│   └── utils/
│       └── benchmark.h         # Inline timing functions
├── src/
│   ├── main.cpp                # Entry point: reads data, runs benchmarks
│   ├── orderbook/
│   │   ├── redblack_tree.cpp
│   │   └── skiplist.cpp
├── frontend/                   # ReactJS frontend (handled by Sai)
│   ├── package.json
│   └── src/
│       ├── App.js
│       └── components/
├── tests/
│   ├── test_redblack_tree.cpp
│   └── test_skiplist.cpp
└── .gitignore                  # Ignore build artifacts, autogenerated files,
editor files */

// TIP See CLion help at <a
// href="https://www.jetbrains.com/help/clion/">jetbrains.com/help/clion/</a>.
//  Also, you can try interactive lessons for CLion by selecting
//  'Help | Learn IDE Features' from the main menu.