#include <iostream>

// TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
int main() {
    // TIP Press <shortcut actionId="RenameElement"/> when your caret is at the
    // <b>lang</b> variable name to see how CLion can help you rename it.
    auto lang = "C++";
    std::cout << "Hello and welcome to " << lang << "!\n";

    for (int i = 1; i <= 5; i++) {
        // TIP Press <shortcut actionId="Debug"/> to start debugging your code.
        // We have set one <icon src="AllIcons.Debugger.Db_set_breakpoint"/>
        // breakpoint for you, but you can always add more by pressing
        // <shortcut actionId="ToggleLineBreakpoint"/>.
        std::cout << "i = " << i << std::endl;
    }

    return 0;
}

/*OrderBookSimulator/
├── README.md                   # Project overview, setup instructions
├── CMakeLists.txt              # Optional, for building C++ backend
├── data/
│   └── generate_data.cpp       # Script to generate random orders
├── include/
│   ├── common/
│   │   ├── macros.h            # Logging macros, constants
│   │   └── types.h             # Order struct, enums (Side, Type)
│   ├── orderbook/
│   │   ├── redblack_tree.h     # Red-Black Tree header
│   │   └── skiplist.h          # Skiplist header
│   └── utils/
│       └── benchmark.h         # Inline timing functions
├── src/
│   ├── main.cpp                # Entry point: reads data, runs benchmarks
│   ├── orderbook/
│   │   ├── redblack_tree.cpp
│   │   └── skiplist.cpp
├── frontend/                   # ReactJS frontend (handled by Sai)
│   ├── package.json
│   └── src/
│       ├── App.js
│       └── components/
├── tests/
│   ├── test_redblack_tree.cpp
│   └── test_skiplist.cpp
└── .gitignore                  # Ignore build artifacts, autogenerated files, editor files */



// TIP See CLion help at <a
// href="https://www.jetbrains.com/help/clion/">jetbrains.com/help/clion/</a>.
//  Also, you can try interactive lessons for CLion by selecting
//  'Help | Learn IDE Features' from the main menu.